### ISSUE TITLE
Missing git config causes build failure dps_for_iot_cmake_module

### ISSUE THREAD

**Issue by raghaprasad** [ros2/rmw_dps#10]
## Bug report

**Required Info:**
- Operating System:
  - Docker container  (osrf/ros2) running Ubuntu Bionic
- Installation type:
  - Build from source 

## Details 

Example build failure here: https://travis-ci.org/raghaprasad/rmw_dps/builds/533025508
When I attempt to build rmw_dps from source on a docker container the build fails with the following error message

`
> colcon build --packages-up-to rmw_dps_cpp
Starting >>> dps_for_iot_cmake_module
--- stderr: dps_for_iot_cmake_module
Cloning into 'ext/mbedtls'...
Cloning into 'ext/safestring'...
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'root@travis-job-7025d075-437d-4f09-a65b-be918c39e50d.(none)')
scons: *** [ext/safestring/makefile] Error 128
make[2]: *** [dps_for_iot/src/dps_for_iot-stamp/dps_for_iot-build] Error 2
make[1]: *** [CMakeFiles/dps_for_iot.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< dps_for_iot_cmake_module	[ Exited with code 2 ]
`

Setting the git config information resolves the issue.

**Comment by malsbat** [comment]
I can't repro this, but I see at https://github.com/ros2/ros2_documentation/blob/c09ccfce781cce3c553ffc70c143e5690940d29b/source/Contributing/Set-up-a-new-Windows-CI-node.rst#id3, they explicitly configure the user.name and user.email.  Can you try that?

**Comment by raghaprasad** [comment]
Yeah we have a branch where it works: https://github.com/raghaprasad/rmw_dps/blob/ragha_dev/.travis.yml

We can use that as a work around for now.

**Comment by malsbat** [comment]
In the page I referenced they use 
> git config --global user.email "noreply@osrfoundation.org"
> git config --global user.name "nobody"
as the configured email and name.

Perhaps you want to use those instead of your email address?

**Comment by raghaprasad** [comment]
Done : https://github.com/ros2/rmw_dps/pull/13
